version: '3.7'
services:

  banco_db:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
      - ../scripts/:/code/scripts/
    expose:
      - 5432
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${PGPORT}
      POPULATE_DB: ${POPULATE_DB}

volumes:
  data: {}
